WARN 5: [filename: 3_3_func_naming_warning_.py, line: 4]: Invalid function name: invalidTopLevel
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 6]: Invalid function name: invalidInner
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 22]: Invalid function name: invalidPublic
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 28]: Invalid function name: _invalidProtected
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 34]: Invalid function name: __invalidPrivate
