WARN 5: [filename: 3_3_func_naming_warning_.py, line: 4, column: 0]: Invalid function name
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 5, column: 4]: Invalid function name
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 20, column: 4]: Invalid function name
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 26, column: 4]: Invalid function name
WARN 5: [filename: 3_3_func_naming_warning_.py, line: 32, column: 4]: Invalid function name
